export const imagesData = [
  {
    itemName: 'First Item',
    itemCategory: 'Category A',
    itemLink: 'https://example.com/item1',
    itemCopy: 'Short description of the first item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Second Item',
    itemCategory: 'Category B',
    itemLink: 'https://example.com/item2',
    itemCopy: 'Short description of the second item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Third Item',
    itemCategory: 'Category C',
    itemLink: 'https://example.com/item3',
    itemCopy: 'Short description of the third item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Fourth Item',
    itemCategory: 'Category A',
    itemLink: 'https://example.com/item4',
    itemCopy: 'Short description of the fourth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Fifth Item',
    itemCategory: 'Category B',
    itemLink: 'https://example.com/item5',
    itemCopy: 'Short description of the fifth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Sixth Item',
    itemCategory: 'Category C',
    itemLink: 'https://example.com/item6',
    itemCopy: 'Short description of the sixth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Seventh Item',
    itemCategory: 'Category A',
    itemLink: 'https://example.com/item7',
    itemCopy: 'Short description of the seventh item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Eighth Item',
    itemCategory: 'Category B',
    itemLink: 'https://example.com/item8',
    itemCopy: 'Short description of the eighth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Ninth Item',
    itemCategory: 'Category C',
    itemLink: 'https://example.com/item9',
    itemCopy: 'Short description of the ninth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
  {
    itemName: 'Tenth Item',
    itemCategory: 'Category A',
    itemLink: 'https://example.com/item10',
    itemCopy: 'Short description of the tenth item.',
    itemImg: `https://source.unsplash.com/random/500x500?sig=${Math.random()}`,
  },
];
